### ISSUE TITLE
Variable named az_counts

### ISSUE THREAD

**Issue by mlosapio** [terraform-community-modules/tf_aws_availability_zones#11]
Documentation has it listed as az_count

**Comment by antonbabenko** [comment]
Yes, you are right. Renaming this variable will break things for some people. Let's keep it as is unless we introduce versioning and use it.

**Comment by bobtfish** [comment]
Lets fix the docs to be consistent with the code however :)

**Comment by bobtfish** [comment]
Waaaait a second - the output for the user is named 'az_count', the intermediate variable is named az_counts, but that's not output from the module.

So it appears to me that the documentation is correct as it documents to output name (i.e. how to use the module) rather than the internals.

Please let me know if I'm being dumb and missing something here?
